name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - seekheart
body:
  - type: textarea
    attributes:
      label: What is the bug?
      description: Give a synopsis of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Give exact steps to reproduce the issue
    validations:
      required: true
  - type: input
    attributes:
      label: What version are you using?
      description: Give the release tag (vX.Y.Z where X,Y,Z are integers for example v1.1.1)
    validations:
      required: true