name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["feature"]
assignees:
  - seekheart
body:
  - type: textarea
    attributes:
      label: What feature are you requesting
      description: What problem are you hoping to solve and how should the feature be used?
    validations:
      required: true
