name: build-publish-docker-image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Get metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: $ {{ secrets.DOCKERHUB_USERNAME }}/jainy_bot

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.ref_name }}