name: build-publish-docker-image
on:
  push:
    branches:
      - develop
      - master
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker.DOCKERHUB_USERNAME }}
          password: ${{ secrets.docker.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: $TAG